/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ArenaConfig, ArenaMatch } from 'dsh-agent-arena/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6167656e744172656e61 {
    applyWinner: (id: string) => Promise<RemoteResult<ArenaMatch>>
    cancel: (id: string) => Promise<RemoteResult<ArenaMatch>>
    get: (id: string) => Promise<RemoteResult<ArenaMatch>>
    list: (limit: number) => Promise<RemoteResult<ArenaMatch[]>>
    start: (input: ArenaConfig) => Promise<RemoteResult<ArenaMatch>>
  }
  interface TypertRemoteMap {
    'agentArena/applyWinner': (id: string) => Promise<RemoteResult<ArenaMatch>>
    'agentArena/cancel': (id: string) => Promise<RemoteResult<ArenaMatch>>
    'agentArena/get': (id: string) => Promise<RemoteResult<ArenaMatch>>
    'agentArena/list': (limit: number) => Promise<RemoteResult<ArenaMatch[]>>
    'agentArena/start': (input: ArenaConfig) => Promise<RemoteResult<ArenaMatch>>
  }
  interface TypertRemoteNamespaceMap {
    'agentArena': TypertRemoteNamespace$6167656e744172656e61
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
